function generateMarkdown(answers) {
  return `
![badge](https://img.shields.io/badge/license-${answers.license}-red)<br />
## Description
 ${answers.description}
## Table of Contents

- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [Credits](#credits)
- [License](#license)
- [Questions](#questions)



## Installation
 ${answers.installation}
## Usage
${answers.usage}
## License
![badge](https://img.shields.io/badge/license-${answers.license}-red)
<br />
This application is covered by the ${answers.license} license. 
## Questions
${answers.questions}<br />
<br />
 Find me on GitHub: [${answers.username}](https://github.com/${answers.username})<br />
<br />
Email me with any questions: ${answers.email}<br /><br />
_This README was generated by [README-generator](https://github.com/jessicaga9410/README-generator) 
  `;
}

module.exports = generateMarkdown;